---
  - name: "vpn"
    hosts: localhost
    become: yes
    become_user: root
    tasks:
      - name: Make sure packages are installed
        package:
          name: ["wireguard-tools", "resolvconf"]
          state: latest
          
      - name: Create startup script
        copy:
          dest: /usr/bin/qubes-wg-manage
          mode: "u+rwx,g+rx,o+rx"
          content: |
            #!/bin/bash
            set -e
            action=$1
            for f in $(ls /home/user/wireguard/*.conf); do
                cp $f /etc/wireguard/$(basename $f)
                echo " >> $(basename -s .conf $f)"
                wg-quick $action $(basename -s .conf $f)
            done
            sleep infinity
            
      - name: Create startup service
        copy:
          dest: /etc/systemd/system/qubes-wireguard.service
          content: |
            [Unit]
            Description=Setup all Wireguard tunnels defined in /home/user/wireguard directory
            Wants=network-online.target
            After=network-online.target

            [Service]
            Type=simple
            ExecStart=/usr/bin/qubes-wg-manage up
            ExecStop=/usr/bin/qubes-wg-manage down

            [Install]
            WantedBy=multi-user.target

      - name: Add Wireguard random endpoint support
        copy:
          dest: /usr/bin/wg-random-endpoint-enable
          content: |
            #!/bin/bash
            set -e
            mkdir -p /home/user/wireguard-random-endpoints
            randomConfig=$(basename -s .conf $(ls /home/user/wireguard-random-endpoints | shuf -n 1))
            echo " >> ${randomConfig}"
            cp /home/user/wireguard-random-endpoints/${randomConfig}.conf ~/wireguard/random-endpoint.conf
            sudo systemctl restart qubes-wireguard
            
      - name: Enable service
        service:
          name: qubes-wireguard
          enabled: yes
