---
  - name: "vpn"
    hosts: localhost
    become: yes
    become_user: root
    tasks:
      - name: Make sure packages are installed
        package:
          name: ["wireguard-tools"]
          state: latest
          
      - name: Create startup script
        copy:
          dest: /usr/local/bin/qubes-wg-manage
          mode: "u+rwx,g+rx,o+rx"
          content: |
            #!/bin/bash
            action=$1
            for f in $(ls /home/user/wireguard/*.conf); do
                cp $f /etc/wireguard/$(basename $f)
                echo " >> $(basename -s .conf $f)"
                wg-quick $action $(basename -s .conf $f)
            done
            
      - name: Create startup service
        copy:
          dest: /etc/systemd/system/qubes-wireguard.unit
          content: |
            [Unit]
            Description=Setup all Wireguard tunnels defined in /home/user/wireguard directory
            Wants=network-online.target
            After=network-online.target

            [Service]
            Type=simple
            ExecStart=/usr/local/bin/qubes-wg-manage up
            ExecStop=/usr/local/bin/qubes-wg-manage down

            [Install]
            WantedBy=multi-user.target
            
      - name: Enable service
        service:
          name: qubes-wg-wireguard
          enabled: yes
